"""
CSV logger for LLM-generated content for evaluation purposes.
"""

import csv
import os
from typing import Optional
import threading

# Thread-safe file writing
_lock = threading.Lock()

# Default CSV path
DEFAULT_CSV_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    'llm_generations.csv'
)

# Character limit for evaluation (configurable)
CHARACTER_LIMIT = 200


def log_llm_generation(
    generated_text: str,
    prompt: str = "",
    csv_path: str = DEFAULT_CSV_PATH
) -> None:
    """
    Log an LLM-generated response to a CSV file for evaluation.
    Simplified format: prompt, generated_text, fun_rating, within_characters
    
    Args:
        generated_text (str): The text generated by the LLM
        prompt (str): The prompt used (optional, for context)
        csv_path (str): Path to the CSV file
    """
    with _lock:
        # Check if file exists to determine if we need headers
        file_exists = os.path.isfile(csv_path)
        
        # Calculate if text is within character limit
        char_count = len(generated_text)
        within_characters = "Yes" if char_count <= CHARACTER_LIMIT else "No"
        
        try:
            with open(csv_path, 'a', newline='', encoding='utf-8') as csvfile:
                fieldnames = [
                    'prompt',
                    'generated_text',
                    'fun_rating',
                    'within_characters'
                ]
                
                # Use QUOTE_ALL to ensure all fields are properly quoted and escaped
                writer = csv.DictWriter(csvfile, fieldnames=fieldnames, quoting=csv.QUOTE_ALL)
                
                # Write header if file is new
                if not file_exists:
                    writer.writeheader()
                
                # Write the generation data
                writer.writerow({
                    'prompt': prompt,
                    'generated_text': generated_text,
                    'fun_rating': '',  # Empty for manual rating
                    'within_characters': within_characters
                })
                
        except Exception as e:
            print(f"Error logging LLM generation to CSV: {e}")


def get_csv_path() -> str:
    """
    Get the path to the CSV file.
    
    Returns:
        str: Path to the CSV file
    """
    return DEFAULT_CSV_PATH
