"""
Ally class for the dungeon crawler game.
"""

import random
from typing import Optional


class Ally:
    """
    Represents an ally that can help the player in combat (one-time use).
    """
    
    def __init__(self, name: str = "", description: str = "", floor: int = 1):
        self.name = name or "Mysterious Helper"
        self.description = description or "A helpful figure appears to aid you in battle."
        self.floor = floor
        
        # Scale attack power based on floor level
        base_attack = 15 + (floor * 3)
        self.attack_power = base_attack + random.randint(-3, 5)
        
        # Ensure minimum attack power
        self.attack_power = max(10, self.attack_power)
        
        # Allies are one-time use, so they don't need health stats
        self.used = False
    
    def use_attack(self) -> int:
        """
        Use the ally's attack (marks ally as used).
        
        Returns:
            int: Damage dealt by the ally
        """
        if self.used:
            return 0
        
        self.used = True
        # Add some randomness to ally attacks
        variation = random.randint(-2, 4)
        return max(5, self.attack_power + variation)
    
    def is_available(self) -> bool:
        """
        Check if the ally is still available for use.
        
        Returns:
            bool: True if ally hasn't been used yet, False if already used
        """
        return not self.used
    
    def to_dict(self) -> dict:
        """
        Convert ally to dictionary for JSON serialization.
        
        Returns:
            dict: Ally data as dictionary
        """
        return {
            "name": self.name,
            "description": self.description,
            "floor": self.floor,
            "attack_power": self.attack_power,
            "used": self.used
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> 'Ally':
        """
        Create ally from dictionary data.
        
        Args:
            data (dict): Ally data dictionary
            
        Returns:
            Ally: Ally object created from data
        """
        ally = cls(
            name=data["name"],
            description=data["description"],
            floor=data["floor"]
        )
        ally.attack_power = data["attack_power"]
        ally.used = data["used"]
        return ally
    
    @classmethod
    def create_random_ally(cls, floor: int = 1, name: str = "", description: str = "") -> 'Ally':
        """
        Create a random ally for the given floor.
        
        Args:
            floor (int): Floor level for scaling power
            name (str): Optional custom name
            description (str): Optional custom description
            
        Returns:
            Ally: Newly created ally
        """
        # If no name/description provided, these will be generated by LLM in generation.py
        return cls(name=name, description=description, floor=floor)
    
    def get_ally_info(self) -> dict:
        """
        Get ally information suitable for display.
        
        Returns:
            dict: Ally information
        """
        return {
            "name": self.name,
            "description": self.description,
            "attack_power": self.attack_power,
            "available": self.is_available()
        }